apiVersion: batch/v1
kind: Job
metadata:
  name: {JOBNAME}
spec:
  # Pulls should not take more than an aggregate of twenty minutes.
  # This will prevent it from spawning pods *forever*, but only for 20min
  activeDeadlineSeconds: 1200
  parallelism: {NODECOUNT}
  completions: {NODECOUNT}
  template:
    metadata:
      labels:
        yuvi.in/pod-puller: "true"
    spec:
      restartPolicy: Never
      containers:
        - image: yuvipanda/image-puller:v0.2
          args: ["{IMAGE}", "{TAG}"]
          name: puller
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values: {NODENAMES}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchLabels:
                "yuvi.in/pod-puller": "true"
      tolerations:
        - operator: Exists
